export default {
  'Charpter2 拼写规范': {
    title: '2.1 通用拼写',
    desc: '下述拼写属于美英通用方式，在考试中不会减分，左右两种都可以',
    columns: ['British', 'American', 'Meaning'],
    rows: [
      ['acknowledgement', 'acknowledgment, acknowledgement', '承认；谢礼'],
      ['adviser', 'advisor', '顾问'],
      ['ageing', 'aging', '衰老的；年老的；过时的'],
      ['aeroplane', 'airplane', '飞机'],
      ['aluminium', 'aluminum', '铝'],
      ['analogue', 'analog', '相似物；类似物；对等物'],
      ['annex, annexe', 'annex', 'v. 吞并；兼并；强占。n. 附属建筑；附加建筑'],
      ['apologize, apologise', 'apologize', '道歉'],
      ['archaeology', 'archeology, archaeology', '考古学'],
      ['artefact', 'artifact, artefact', '人工制品；手工艺品'],
      ['axe', 'ax, axe', '斧头'],
      ['analyse, analyze', 'analyze', '分析'],
      ['behaviour', 'behavior', '行为；举止'],
      ['cancelled', 'canceled, cancelled', '取消；终止；撤销'],
      ['catalogue', 'catalog', 'n. 目录册；目录；一系列（坏的事情）。v. 记录；将...编入目录'],
      ['centre', 'center', '中心；中央'],
      ['cheque', 'check', '支票'],
      ['chilli, chili', 'chili', '辣椒'],
      ['colour', 'color', '颜色'],
      ['cosy', 'cozy', '（尤指建筑物因为小及温暖而）温馨的；温暖舒适的；惬意的；安逸的'],
      ['counsellor', 'counselor', '顾问；辅导员；律师'],
      ['critcise, critcize', 'criticize', '批评；指责；评论'],
      ['defence', 'defense', '防御；辩护'],
      ['dialogue', 'dialog', '对话；对白'],
      ['disc, disk', 'disk', '圆盘；光盘'],
      ['doughnut', 'donut, doughnut', '炸面包圈'],
      ['emphasise', 'emphasize', '强调；重视；使突出；使明显'],
      ['enquiry, inquiry', 'inquiry', '询问；打听；调查；研究'],
      ['enrol', 'enroll', '使加入；注册；招生；吸收'],
      ['favour', 'favor', '支持；赞同；帮助；恩惠'],
      ['fibre', 'fiber', '纤维；丝；纤维素；品质'],
      ['flavour', 'flavor', '风味；特点'],
      ['fulfil', 'fulfill, fulfil', '实现；达到；满足'],
      ['glamour', 'glamour, glamor', '吸引力；魅力；诱惑力'],
      ['grey', 'gray', '灰色的；阴沉的'],
      ['harbour', 'harbor', '港口'],
      ['honour', 'honor', '名誉；荣誉'],
      ['jail, gaol', 'jail', '监狱；看守所'],
      ['jewellery', 'jewelry', '珠宝；首饰'],
      ['judgement', 'judgment', '判断；判断力；审判'],
      ['kerb', 'curb', 'n. （道路的）路缘'],
      ['kilometre', 'kilometer', '千米；公里'],
      ['labour', 'labor', '劳动；劳工'],
      ['licence', 'license', '许可；许可证'],
      ['litre', 'liter', '升'],
      ['manoeuvre', 'maneuver', 'n. 精巧动作；军事演习；技巧；花招。v. 操纵；控制'],
      ['metre', 'meter', '米'],
      ['mould', 'mold', '霉菌；模具'],
      ['naught', 'nought', '无；没有；零'],
      ['neighbour', 'neighbor', '邻居；邻国'],
      ['offence', 'offense', '罪行；得罪'],
      ['organisation', 'organization', '组织；机构'],
      ['parlour', 'parlor', '店堂；店铺；起居室；客厅'],
      ['plough', 'plow', 'n. 犁。v. 犁；耕'],
      ['practise', 'practice', 'v. 实施；练习'],
      ['practice', 'practice', 'n. 习俗；惯例；训练'],
      ['pyjamas', 'pajamas', '睡衣裤'],
      ['realise', 'realize', '明白；意识到；实现；变现'],
      ['rigour', 'rigor', '严厉；严格；严苛；严密；缜密'],
      ['saviour', 'savior', '救助者；救星'],
      ['savour', 'savor', 'v. 细品；享用。n. 乐趣；情趣'],
      ['sceptical', 'skeptical', '怀疑的；持怀疑态度的'],
      ['skilfu', 'skillful, skilful', '熟练的；出色的'],
      ['speciality', 'specialty', '（注意两个词发音不一样）特产；专长'],
      ['sulphur', 'sulfur', '硫；硫磺'],
      ['theatre', 'theater', '剧院；电影院；剧本'],
      ['traveller', 'traveler', '旅行者；旅客'],
      ['travelling', 'traveling, travelling', '旅行；巡回的'],
      ['tyre', 'tire', '轮胎'],
      ['vice', 'vise, vice', '副职的；堕落；恶习'],
      ['vigour', 'vigor', '体力；活力；气力；气势；力量'],
      ['woollen', 'woolen', '羊毛制成的'],
    ],
  },
}
