export default {
  'Charpter2 拼写规范': {
    title: '2.1 通用拼写',
    desc: '下述拼写属于美英通用方式，在考试中不会减分，左右两种都可以',
    columns: ['British', 'American', 'Meaning'],
    rows: [
      ['acknowledgement', 'acknowledgment, acknowledgement', '承认；谢礼'],
      ['adviser', 'advisor', '顾问'],
      ['ageing', 'aging', '衰老的；年老的；过时的'],
      ['aeroplane', 'airplane', '飞机'],
      ['aluminium', 'aluminum', '铝'],
      ['analogue', 'analog', '相似物；类似物；对等物'],
      ['annex, annexe', 'annex', 'v. 吞并；兼并；强占。n. 附属建筑；附加建筑'],
      ['apologize, apologise', 'apologize', '道歉'],
      ['archaeology', 'archeology, archaeology', '考古学'],
      ['artefact', 'artifact, artefact', '人工制品；手工艺品'],
      ['axe', 'ax, axe', '斧头'],
      ['analyse, analyze', 'analyze', '分析'],
      ['behaviour', 'behavior', '行为；举止'],
      ['cancelled', 'canceled, cancelled', '取消；终止；撤销'],
      ['catalogue', 'catalog', 'n. 目录册；目录；一系列（坏的事情）。v. 记录；将...编入目录'],
      ['centre', 'center', '中心；中央'],
      ['cheque', 'check', '支票'],
      ['chilli, chili', 'chili', '辣椒'],
      ['colour', 'color', '颜色'],
      ['cosy', 'cozy', '（尤指建筑物因为小及温暖而）温馨的；温暖舒适的；惬意的；安逸的'],
      ['counsellor', 'counselor', '顾问；辅导员；律师'],
      ['critcise, critcize', 'criticize', '批评；指责；评论'],
      ['defence', 'defense', '防御；辩护'],
      ['dialogue', 'dialog', '对话；对白'],
      ['disc, disk', 'disk', '圆盘；光盘'],
      ['doughnut', 'donut, doughnut', '炸面包圈'],
      ['emphasise', 'emphasize', '强调；重视；使突出；使明显'],
      ['enquiry, inquiry', 'inquiry', '询问；打听；调查；研究'],
      ['enrol', 'enroll', '使加入；注册；招生；吸收'],
      ['favour', 'favor', '支持；赞同；帮助；恩惠'],
    ],
  },
}
