const sentences = [
  {
    no: 1,
    sentence: '经常做运动会提高人的自信',
    translationFromBook: 'Regular exercise can increase one\'s self-confidence',
    chatgpt: 'Frequently exercising can increase one\'s confidence',
    remark: '',
  },
  {
    no: 2,
    sentence: '教学质量对学生成绩有很大的影响',
    translationFromBook: 'The quality of teaching can make huge deffernce to students\' academic performance',
    chatgpt: 'Academic achievement is heavily dependent on the quality of teaching',
    remark: '',
  },
  {
    no: 3,
    sentence: '家长和老师应该努力去减少小孩子看电视的时间',
    translationFromBook: 'Parents and teachers should make an effort to limit children’s screen time',
    chatgpt: 'Parents and teachers should make efforts to reduce the screen time of children',
    remark: '',
  },
  {
    no: 4,
    sentence: '经济的下滑（economic slowdown）导致失业率的上升',
    translationFromBook: 'The economic slowdown has led to a climbing unemployment rate.',
    chatgpt: 'The economic slowdown has led to an increase in the unemployment rate —— increase 本身有名词词性',
    remark: '',
  },
  {
    no: 5,
    sentence: '经济的发展需要年轻的劳动者',
    translationFromBook: 'A country’s economic development relies on a supply of young workers',
    chatgpt: '',
    remark: '',
  },
  {
    no: 6,
    sentence: '工作量大的人没有时间去休息',
    translationFromBook: 'A country’s economic development relies on a supply of young workers',
    chatgpt: '',
    remark: '',
  },
  {
    no: 7,
    sentence: '在中国很多学生都要上晚自习 ',
    translationFromBook: 'A large number of students in China have to do self-study at night',
    chatgpt: '',
    remark: '',
  },
  {
    no: 8,
    sentence: '文化遗产（heritage sites）因为城市发展而受到威胁',
    translationFromBook: 'The development of cities has posed a threat to heritage sites',
    chatgpt: '',
    remark: 'pose a threat 构成威胁',
  },
  {
    no: 9,
    sentence: '我们不能忽视面对面的交流',
    translationFromBook: 'We should not ignore face-to-face communication',
    chatgpt: '',
    remark: '',
  },
  {
    no: 10,
    sentence: '有些公共服务很难做到收支平衡',
    translationFromBook: 'Some public services have problems in breaking even',
    chatgpt: 'Some public services are challenging to achieve a balance between revenue and expenses/Some public services find it challenging to break even',
    remark: 'break even 收支平衡',
  },
  {
    no: 11,
    sentence: '我们需要考虑社会和经济环境',
    translationFromBook: 'We have to consider the social and economic context',
    chatgpt: 'We need to consider the social and economic environment',
    remark: '',
  },
  {
    no: 12,
    sentence: '密度种植对生物多样性造成了威胁',
    translationFromBook: 'Intensive farming can pose a threat to bio-diversity',
    chatgpt: 'Intensive cultivation poses a threat to biodiversity',
    remark: '',
  },
  {
    no: 13,
    sentence: '平等接受教育可以帮助解决学生学习成绩不好的问题',
    translationFromBook: 'Equal access to education can help tackle educational underachievement',
    chatgpt: 'Equal access to education can help tackle the issue of students\' academic underachievement',
    remark: '注意这里的 help 后面的 to 是可以省略的，类似的：make/let/hear/feel/watch 等。underachievement n. 低成就；学习成绩不良',
  },
  {
    no:  14,
    sentence: '接触不同的文化可以促进创新',
    translationFromBook: 'Exposure to different cultures can encourage creativity',
    chatgpt: 'Exposure to different cultures can promote innovation',
    remark: '注意 culture 这个词多数情况下是不可数的，表示不同地方、特定文化的时候才可数',
  },
  {
    no:  15,
    sentence: '政府应该重视社会福利（welfare services），尤其是医疗服务',
    translationFromBook: 'The government should give priority to welfare services especially healthcare',
    chatgpt: 'The government should prioritize welfare services, especially healthcare',
    remark: '',
  },
  {
    no:  16,
    sentence: '教育或许决定了人的工作前景',
    translationFromBook: 'Education may hold the key to one\'s job prospects',
    chatgpt: 'Education might shape one\'s career prospects',
    remark: 'hold the key 掌控，支配。prospects 成功的机会；前景，前途',
  },
  {
    no:  17,
    sentence: '使用化石燃料会对环境造成破坏',
    translationFromBook: 'The use of fossil fuels can cause damage to the environment',
    chatgpt: 'Using fossil fuels can cause environmental damage',
    remark: 'fuel 的可数和不可数的问题，表示一般的燃料的概念时不可数，不同种类时可数，例如这里 fossil fuels 表示的可能是煤、天然气、石油等...',
  },
  {
    no:  18,
    sentence: '建造住宅楼有助于解决城市的拥挤问题',
    translationFromBook: 'Building apartment blocks helps (to) solve overcrowding in cities',
    chatgpt: 'Constructing residential buildings helps (to) alleviate urban congestion',
    remark: 'alleviate v. 减轻；缓和；缓解',
  },
  {
    no: 19,
    sentence: '贫穷的人可以通过努力工作来提高其社会地位',
    translationFromBook: 'People from disadvantaged backgrounds can improve their social status by working hard.',
    chatgpt: 'The impoverished can improve their social status through/via hard work',
    remark: '',
  },
  {
    no: 20,
    sentence: '因为全球化，人们需要和来自全球不同背景的人一起工作',
    translationFromBook: 'Because of globalization, people need to work with those from diverse backgrounds',
    chatgpt: 'Due to globalization, people need to work with individuals from diverse backgrounds around the world',
    remark: 'ChatGPT 给的另一个表达：Due to globalization, those from diverse backgounds around the world need to work togather',
  },
  {
    no: 21,
    sentence: ' 我们需要采取措施去解决一些棘手的问题',
    translationFromBook: 'We need to take action to solve some thorny problems',
    chatgpt: 'We need to take measures to address some challenging issues',
    remark: 'thorny adj. 棘手的，麻烦的；多刺的，带刺的。thorn n. 刺，荆棘',
  },
  {
    no: 22,
    sentence: '媒体通过夸大受害者的伤痛去吸引观众',
    translationFromBook: 'The media attracts public attention by sensationalizing victims\' suffering',
    chatgpt: 'The media attracts viewers by exaggerating the pain of victims',
    remark: '',
  },

  {
    no: '',
    sentence: '',
    translationFromBook: '',
    chatgpt: '',
    remark: '',
  },
]

export default sentences